name: build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4


      - name: Install tooling
        run: |
          sudo apt update
          sudo apt install build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi python3

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build

      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/*.uf2
           
